# Final P1 parameters (train set: 2021-01-01..2024-12-31) - UPDATED 2025-09-29
m_kcal_per_day: 1400      # M (updated from 1630)
compensation_c: 0.50      # C (updated from 0.19)
alpha_kcal_per_kg: 9500   # Î± (updated from 9800)
window_days: 7

# DB connection (override via env if you prefer)
db:
  host: localhost
  port: 5432
  user: markhill
  password: ""            # or set P1_DB_PASSWORD in env
  database: markhill
  sslmode: disable
